### PR TITLE
Update to Scala 2.12.0 only agni-core

### PR DESCRIPTION
**Pull request by tkrs**
`agni-twitter-util` is missing dependencies still for the scala 2.12. So, it is not supported now.

---
This change is [Reviewable](https://reviewable.io/reviews/yanana/agni/40)

### CODE REVIEW

**Comment by yanana** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

_[build.sbt, line 26 at r1](https://reviewable.io:443/reviews/yanana/agni/40#-KWGpGZRNd8f55mGUtDR:-KWGpGZRNd8f55mGUtDS:bzfyq8h) ([raw file](https://github.com/yanana/agni/blob/223e2847f8bf9eca2791658a198eefd5eeee9888/build.sbt#L26)):_

> ``` Scala
>   "org.typelevel" %% "cats" % catsVersion,
>   "com.chuusai" %% "shapeless" % shapelessVersion,
>   "org.scodec" %% "scodec-bits" % "1.1.0"
> ```

Why are `ByteVector`/`BitVector` support removed?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/yanana/agni/40)_

**Comment by tkrs** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

_[build.sbt, line 26 at r1](https://reviewable.io:443/reviews/yanana/agni/40#-KWGpGZRNd8f55mGUtDR:-KWGpoUFhfb3zle96iE8:b-9gvk17) ([raw file](https://github.com/yanana/agni/blob/223e2847f8bf9eca2791658a198eefd5eeee9888/build.sbt#L26)):_
<details><summary>

<i>Previously, yanana (Shun Yanaura) wrote…</i></summary>



> Why are `ByteVector`/`BitVector` support removed?
> </details>
> I think that it is not necessary to be dependent on core. Those who need may be implementation using `NamedColumnGetter` and `IndexedColumnGetter`.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/yanana/agni/40)_

**Comment by yanana** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

_[build.sbt, line 26 at r1](https://reviewable.io:443/reviews/yanana/agni/40#-KWGpGZRNd8f55mGUtDR:-KWHIxd81ab1bgIx-Rfw:b-837i3v) ([raw file](https://github.com/yanana/agni/blob/223e2847f8bf9eca2791658a198eefd5eeee9888/build.sbt#L26)):_
<details><summary>

<i>Previously, tkrs (Takeru Sato) wrote…</i></summary>



> I think that it is not necessary to be dependent on core. Those who need may be implementation using `NamedColumnGetter` and `IndexedColumnGetter`.
> </details>
> Okay.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/yanana/agni/40)_

**Comment by yanana** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/yanana/agni/40)_

**Comment by yanana** [comment]
## LGTM 

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/yanana/agni/40#-:-KWHJx5MxZsRBp_12qUU:b32uxc)_

**Pull request merged**
