### PR TITLE
Build for JDK 11 / EA

### LINKED ISSUE #104: Build for java 11 / EA

### PR DESCRIPTION
**Pull request by tkrs**
Closes #104

### CODE REVIEW

**Comment by tkrs** [comment]
@yanana I think that this [error](https://travis-ci.org/yanana/agni/jobs/448241774#L853) occurred probably because the PGP private key file is an empty. Could you please confirm it?

**Comment by yanana** [comment]
@tkrs I know. I'm going to try it later. Sorry for letting you wait.

**Comment by yanana** [comment]
@tkrs It looks like the environment variable `PGP_SECRET_RING_PATH` have to be read and configured to pass to sbt-pgp in build.sbt explicitly.

**Comment by tkrs** [comment]
It looks like it is configured.

https://github.com/yanana/agni/blob/8e41fb829e723c37c988e40dc49dba84ba5175dc/sonatype.sbt#L6

**Comment by yanana** [comment]
@tkrs I've tried for a long time, and eventually Travis builds succeeded. Would you please rebase onto the current master?

**Comment by tkrs** [comment]
@yanana https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions 
> Pull requests sent from forked repositories do not have access to encrypted variables or data.

Sorry, I didn't know that...

**Comment by yanana** [comment]
Oh, I've completely understood the cause of the issues! Thanks anyway!

**Review by yanana — APPROVED** [review]
LGTM

**Pull request merged**
